server:
  port: 8080

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:postgresql://localhost:5432/sec_test
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:8080

logging:
  level:
    org.springframework.security: DEBUG

app:
  security:
    jwt:
      key-id: auth-key
      key-pair:
        location: classpath:jwt.pem